name: Update Image Index

on:
  push:
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate image index
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = require('path');

          const dir = './images';
          const files = fs.readdirSync(dir).filter(f => /\.(jpg|jpeg|png|gif)$/i.test(f));
          const metadata = files.map(f => ({
            filename: f,
            title: path.parse(f).name.replace(/[-_]/g, ' '),
            date: new Date().toISOString().split('T')[0],
            telescope: 'Unknown'
          }));

          fs.writeFileSync(path.join(dir, 'index.json'), JSON.stringify(metadata, null, 2));
          EOF

      - name: Commit and push index.json
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add images/index.json
          git commit -m "Auto-update image metadata"
          git push
